{
  imports = [
    ./alacritty.nix
    ./bash.nix
    ./broot.nix
    ./cava.nix
    ./direnv.nix
    ./fastfetch.nix
    ./fish.nix
    ./fzf.nix
#    ./gdb.nix
    ./ghostty.nix
    ./git.nix
    ./helix.nix
    ./hyprland.nix
    ./kitty.nix
    ./lsd.nix
    ./oh-my-posh.nix
    ./proxychains.nix
    ./rofi.nix
    ./starship.nix
    ./tmux.nix
    ./wofi.nix
    ./zed.nix
    ./zellij.nix
    ./zoxide.nix
    ./zsh.nix
  ];
}