{
  imports = [
    ./airline.nix
    ./alpha.nix
    ./colorscheme.nix
    ./comment.nix
    ./cmp.nix
    ./floaterm.nix
    ./harpoon.nix
    ./illuminate.nix
    ./indent-blankline.nix
    ./lazygit.nix
    ./lint.nix
    ./lsp.nix
    ./lualine.nix
    ./mini.nix
    ./navic.nix
    # ./neotree.nix
    ./neo-tree.nix
    ./nixplugin.nix
    ./notify.nix
    ./obsidian.nix
    ./oil.nix
    ./telescope.nix
    ./tmux-navigation.nix
    ./todo-comments.nix
    ./transparent.nix
    ./treesitter.nix
    ./web-devicons.nix
    ./whichkey.nix
    ./autopairs.nix
  ];
}